version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chinh.phan/php
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/log/:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: emole
      MYSQL_ROOT_PASSWORD: Chinh@123123
    volumes:
      # - ./docker/mysql/mysql-dump/:/docker-entrypoint-initdb.d
      # - ./docker/mysql/dbdata/:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  adminer:
    image: adminer:4.8.0
    ports:
      - 8989:8080
    restart: always
    networks:
      - app-network
volumes:
  db_data:
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
