version: "3"
services:
  #PHP Service
  app_emole:
    build:
      context: .
      dockerfile: Dockerfile
    image: chinh.phan/php
    container_name: app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver_emole:
    image: nginx:alpine
    container_name: webserver_emole
    restart: always
    tty: true
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/log/:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db_emole:
    image: mysql:5.7
    container_name: db_emole
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: emole
      MYSQL_ROOT_PASSWORD: Chinh@123123
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      # - ./docker/mysql/mysql-dump/:/docker-entrypoint-initdb.d
      # - ./docker/mysql/dbdata/:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  manage_db_emole:
    image: adminer:latest
    ports:
      - 8989:8080
    restart: always
    networks:
      - app-network
volumes:
  db_data:
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
